// Supabase hello script
// Usage:
// 1) Create the `messages` table in your Supabase project (SQL editor):
//
//   create table public.messages (
//     id bigint generated by default as identity primary key,
//     text text,
//     inserted_at timestamptz default now()
//   );
//
//   -- (Optional for testing only) Allow anon to insert/select
//   grant insert, select on public.messages to anon;
//
// 2) Set environment variables:
//    - SUPABASE_URL (e.g. https://xyz.supabase.co)
//    - SUPABASE_KEY (use a service_role key for creating tables or anon key for simple inserts if the table/policies allow)
// 3) Run: `node scripts/supabase_hello.js`

const process = require('node:process');

async function ensureFetch() {
  if (typeof fetch === 'undefined') {
    try {
      global.fetch = require('node-fetch');
    } catch (err) {
      console.error('fetch is not available. Install node-fetch or run on Node 18+');
      process.exit(1);
    }
  }
}

async function insertMessage(supabaseUrl, supabaseKey, text) {
  const url = `${supabaseUrl.replace(/\/$/,'')}/rest/v1/messages`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'apikey': supabaseKey,
      'Authorization': `Bearer ${supabaseKey}`,
      'Content-Type': 'application/json',
      'Prefer': 'return=representation'
    },
    body: JSON.stringify({ text })
  });
  const body = await res.text();
  let json;
  try { json = JSON.parse(body); } catch(e) { json = body; }
  return { status: res.status, body: json };
}

async function readMessages(supabaseUrl, supabaseKey) {
  const url = `${supabaseUrl.replace(/\/$/,'')}/rest/v1/messages?select=*`;
  const res = await fetch(url, {
    headers: {
      'apikey': supabaseKey,
      'Authorization': `Bearer ${supabaseKey}`,
      'Accept': 'application/json'
    }
  });
  const json = await res.json();
  return json;
}

async function main(){
  await ensureFetch();
  const SUPABASE_URL = process.env.SUPABASE_URL || process.env.SUPABASE_API_URL;
  const SUPABASE_KEY = process.env.SUPABASE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY;
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.error('Missing environment variables. Set SUPABASE_URL and SUPABASE_KEY.');
    process.exit(1);
  }

  console.log('Inserting message "hello"...');
  const insert = await insertMessage(SUPABASE_URL, SUPABASE_KEY, 'hello');
  console.log('Insert response:', insert);

  console.log('Reading messages...');
  const rows = await readMessages(SUPABASE_URL, SUPABASE_KEY);
  console.log('Messages:', rows);
}

main().catch(err => { console.error(err); process.exit(1); });
